
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author A Z E R O T H
 */

import controller.*;
import javax.swing.JOptionPane;

public class loginView extends javax.swing.JFrame {
    
    controlLoginReg controllers;
    /**
     * Creates new form loginView
     */
    public loginView() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setLayout(null);
        
        controllers = new controlLoginReg(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_InputName = new javax.swing.JTextField();
        login_ResetUser = new javax.swing.JButton();
        login_InputPassword = new javax.swing.JPasswordField();
        login_ResetPW = new javax.swing.JButton();
        login_LoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login_SignUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 78, 78));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        login_ResetUser.setBackground(new java.awt.Color(255, 105, 97));
        login_ResetUser.setText("Reset");
        login_ResetUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ResetUserActionPerformed(evt);
            }
        });

        login_ResetPW.setBackground(new java.awt.Color(255, 105, 97));
        login_ResetPW.setText("Reset");
        login_ResetPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_ResetPWActionPerformed(evt);
            }
        });

        login_LoginButton.setBackground(new java.awt.Color(108, 206, 255));
        login_LoginButton.setFont(new java.awt.Font("Rockwell", 3, 12)); // NOI18N
        login_LoginButton.setText("Login!");
        login_LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_LoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        jLabel1.setText("Username :");

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        jLabel2.setText("Password :");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel3.setText("Login Page");

        jLabel4.setText("Didnt Have Account Yet ? ");

        login_SignUpButton.setForeground(new java.awt.Color(108, 206, 255));
        login_SignUpButton.setText("Register");
        login_SignUpButton.setBorderPainted(false);
        login_SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_SignUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_InputName, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(login_InputPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_ResetUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(login_ResetPW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_SignUpButton)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(login_LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(login_ResetUser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(login_InputName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(login_InputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(login_ResetPW)))
                .addGap(20, 20, 20)
                .addComponent(login_LoginButton)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(login_SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_LoginButtonActionPerformed
        String inputusername = login_InputName.getText();
        String inputpw = new String(login_InputPassword.getPassword());
        if (inputusername.equals("") || inputpw.equals("")) {
            JOptionPane.showMessageDialog(this, "Password / Username belum diisi", "Login Error", JOptionPane.ERROR_MESSAGE);}
        else{
            if (controllers.checkUsername(inputusername, inputpw) == 2) {
                dispose();
                new viewAdmin();
            } else if(controllers.checkUsername(inputusername, inputpw) == 1){
                dispose();
                new viewUser(inputusername);
            }else {
                    
                JOptionPane.showMessageDialog(this, "Password salah / Username Salah", "Login Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_login_LoginButtonActionPerformed

    private void login_ResetUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ResetUserActionPerformed
        login_InputName.setText("");
    }//GEN-LAST:event_login_ResetUserActionPerformed

    private void login_SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_SignUpButtonActionPerformed
        new regView();
        dispose();
    }//GEN-LAST:event_login_SignUpButtonActionPerformed

    private void login_ResetPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_ResetPWActionPerformed
        login_InputPassword.setText("");
    }//GEN-LAST:event_login_ResetPWActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField login_InputName;
    private javax.swing.JPasswordField login_InputPassword;
    private javax.swing.JButton login_LoginButton;
    private javax.swing.JButton login_ResetPW;
    private javax.swing.JButton login_ResetUser;
    private javax.swing.JButton login_SignUpButton;
    // End of variables declaration//GEN-END:variables
}
