/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.controlmov;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.movie;

/**
 *
 * @author A Z E R O T H
 */
public class viewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form viewAdmin
     */
    int cursid;
    controlmov controllers;
    String namaKolom[] = {"ID", "Movie Name", "Movie Duration", "Movie Description", "Movie Schedule"};
    DefaultTableModel tm;
    public viewAdmin() {
        initComponents();
        tm = new DefaultTableModel(namaKolom, 0);
        movieTable.setModel(tm);
        setVisible(true);
        controllers = new controlmov(this);
        controllers.showAllMovieadmin();
    }
    
    public void tampilkanDataMovie(List<movie> daftarMovie) {
        tm.setRowCount(0); // Hapus data lama
        for (movie m : daftarMovie) {
            Object[] row = {
                m.getid(),
                m.getname(),
                m.getduration(),
                m.getdescription(),
                m.getSchedule()
            };
            tm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        movieTable = new javax.swing.JTable();
        admin_InsertButton = new javax.swing.JButton();
        admin_UpdateButton = new javax.swing.JButton();
        admin_deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        movieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        movieTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(movieTable);

        admin_InsertButton.setBackground(new java.awt.Color(108, 206, 255));
        admin_InsertButton.setText("Insert");
        admin_InsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_InsertButtonActionPerformed(evt);
            }
        });

        admin_UpdateButton.setBackground(new java.awt.Color(108, 206, 255));
        admin_UpdateButton.setText("Update");
        admin_UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_UpdateButtonActionPerformed(evt);
            }
        });

        admin_deleteButton.setBackground(new java.awt.Color(255, 105, 97));
        admin_deleteButton.setText("Delete");
        admin_deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setText("MANAGE MOVIES");

        logout.setBackground(new java.awt.Color(255, 100, 110));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(admin_InsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(admin_UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(admin_deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin_InsertButton)
                    .addComponent(admin_UpdateButton)
                    .addComponent(admin_deleteButton)
                    .addComponent(logout))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_deleteButtonActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this movie?", 
            "Confirm Delete", 
            javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            controllers.delete(cursid);
            new viewAdmin();
            dispose();
        }
    }//GEN-LAST:event_admin_deleteButtonActionPerformed

    private void admin_InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_InsertButtonActionPerformed
        dispose();
        new  inputMovie();
    }//GEN-LAST:event_admin_InsertButtonActionPerformed

    private void movieTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieTableMouseClicked
        cursid = (int) movieTable.getValueAt(movieTable.getSelectedRow(), 0);
    }//GEN-LAST:event_movieTableMouseClicked

    private void admin_UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_UpdateButtonActionPerformed
    int selectedRow = movieTable.getSelectedRow();
    if (selectedRow != -1) {
        cursid = (int) movieTable.getValueAt(selectedRow, 0);
        String name = (String) movieTable.getValueAt(selectedRow, 1);
        int duration = (int) movieTable.getValueAt(selectedRow, 2);
        String description = (String) movieTable.getValueAt(selectedRow, 3);
        String schedule = (String) movieTable.getValueAt(selectedRow, 4);

        movie mov = new movie();
        mov.setData(cursid, name, description, schedule, duration);

        updatemovie updateForm = new updatemovie(); // buat form baru
        controllers.updatepage = updateForm; // inisialisasi field 'updatepage' di controller
        controllers.dataSelected(cursid, name, duration, description, schedule); // isi data
        updateForm.setVisible(true); // tampilkan form
        dispose(); // tutup form admin (opsional)
    }
    }//GEN-LAST:event_admin_UpdateButtonActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new loginView();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_InsertButton;
    private javax.swing.JButton admin_UpdateButton;
    private javax.swing.JButton admin_deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JTable movieTable;
    // End of variables declaration//GEN-END:variables
}
